---
# vars file for /home/ansible/roles/vadim.nagios-server
package_list:
  - gcc
  - glibc
  - glibc-common
  - gd
  - gd-devel
  - make
  - net-snmp
  - openssl-devel
  - httpd
  - php
  - unzip
  - wget
  - postfix
  - perl
  - python-passlib

nagios_version: 4.4.6

command_list:
  - "./configure"
  - "make all"
  - "make install-groups-users"
  - "usermod -aG nagios apache"
  - "make install"
  - "make install-daemoninit"
  - "make install-commandmode"
  - "make install-config"
  - "make install-webconf"

plugins_version: 2.3.3

plugin_commands_list:
  - "./configure"
  - "make"
  - "make install"

admin_email: root@localhost

admin_password: password
