---
# vars file for /home/ansible/roles/vadim.mysql
package_list:
  - httpd
  - mariadb
  - mariadb-server
  - MySQL-python
  - php
  - php-mysql
  - phpmyadmin

service _list:
  - httpd
  - mariadb
  
roots_passwd: password

firewall_services:
  - http
  - mysql

ip_range: "192.168.1.0/24"  

